export const Continents = [
  {
    name: "europe",
    translatedName: "Europa",
    carousel: "/europe/europe.png",
    banner: "/europe/europeBanner.png",
    bannerTitle: "O continente mais antigo.",
    description:
      "A Europa é, por convenção, um dos seis continentes do mundo. Compreendendo a península ocidental da Eurásia, a Europa geralmente divide-se da Ásia a leste pela divisória de águas dos montes Urais, o rio Ural, o mar Cáspio, o Cáucaso, e o mar Negro a sudeste",
    countryCount: 50,
    languages: 60,
    cities100: 27,
    cities: [
      {
        banner: "/europe/london.png",
        capital: "Londres",
        country: "Reino Unido",
        image: "/europe/england.png",
      },
      {
        banner: "/europe/paris.png",
        capital: "Paris",
        country: "França",
        image: "/europe/france.png",
      },
      {
        banner: "/europe/roma.png",
        capital: "Roma",
        country: "Itália",
        image: "/europe/italy.png",
      },
      {
        banner: "/europe/praga.png",
        capital: "Praga",
        country: "República Tcheca",
        image: "/europe/theca.png",
      },
      {
        banner: "/europe/amsterdam.png",
        capital: "Amsterdã",
        country: "Holanda",
        image: "/europe/nederland.png",
      },
    ],
  },
  {
    name: "asia",
    translatedName: "Ásia",
    carousel: "/asia/asia.jpg",
    banner: "/asia/asiaPage.jpg",
    bannerTitle: "O continente mais populoso.",
    description:
      "A Ásia é o maior dos continentes, tanto em área como em população. Abrange um terço das partes sólidas da superfície da Terra e é responsável por abrigar quase três quintos da população mundial. A Ásia faz fronteira no lado ocidental com a África e com a Europa, e no lado oriental com o oceano Pacífico, a Oceania e, em menor proporção, com a América do Norte, pelo Estreito de Bering.",
    countryCount: 50,
    languages: 2.301,
    cities100: 27,
    cities: [
      {
        banner: "/asia/riyadh.jpg",
        capital: "Riyadh",
        country: "Arabia Saudíta",
        image: "/asia/arabiaSaudita.png",
      },
      {
        banner: "/asia/haLong.jpg",
        capital: "Ha Long",
        country: "Vietnã",
        image: "/asia/vietnã.png",
      },
      {
        banner: "/asia/moscow.png",
        capital: "Moscow",
        country: "Russia",
        image: "/asia/russia.png",
      },
      {
        banner: "/asia/jaipur.jpg",
        capital: "Jaipur",
        country: "India",
        image: "/asia/india.png",
      },
      {
        banner: "/asia/johorBahru.jpg",
        capital: "Johor Bahru",
        country: "Malaysia",
        image: "/asia/malaysia.png",
      },
      {
        banner: "/asia/chennai.jpg",
        capital: "Chennai",
        country: "India",
        image: "/asia/india.png",
      },
    ],
  },
  {
    name: "south-america",
    translatedName: "América do Sul",
    carousel: "/south-america/southAmerica.jpg",
    banner: "/south-america/southAmericaPage.jpg",
    bannerTitle: " Continente com clima tropical e Grande biodiversidade..",
    description:
      "A América do Sul é um continente que compreende a porção meridional da América. Também é considerada um subcontinente do continente americano. A sua extensão é de 17 819 100 km², abrangendo 12% da superfície terrestre e 6% da população mundial. Une-se à América Central a norte pelo istmo do Panamá e se separa da Antártida ao sul pelo estreito de Drake. Tem uma extensão de 7 500 km desde o mar do Caribe até ao cabo Horn, ponto extremo sul do continente. Os outros pontos extremos da América do Sul são: ao norte a Punta Gallinas, na Colômbia, ao leste a Ponta do Seixas, no Brasil, e a oeste a Punta Pariñas, no Peru.",
    countryCount: 12,
    languages: 456,
    cities100: 27,
    cities: [
      {
        banner: "/south-america/rioJaneiro.jpg",
        capital: "Rio de Janeiro",
        country: "Brasil",
        image: "/south-america/brazil.png",
      },
      {
        banner: "/south-america/lima.jpg",
        capital: "Lima",
        country: "Peru",
        image: "/south-america/peru.png",
      },
      {
        banner: "/south-america/buenosAires.jpg",
        capital: "Buenos Aires",
        country: "Argentina",
        image: "/south-america/argentina.png",
      },
      {
        banner: "/south-america/salarAyuni.jpg",
        capital: "Andes",
        country: "Bolivia",
        image: "/south-america/bolivia.png",
      },
    ],
  },
  {
    name: "north-america",
    translatedName: "América do Norte",
    carousel: "/north-america/northAmerica.jpg",
    banner: "/north-america/northAmericaPage.jpg",
    bannerTitle: " Continente com clima tropical e Grande biodiversidade..",
    description:
      "A América do Norte é um subcontinente que compreende a porção setentrional do continente americano. Existem duas formas de classificar esse continente: a primeira considera que a América do Norte é apenas a parte mais setentrional da América, separada da América Central na fronteira entre o México e a Guatemala, a segunda classificação reconhece apenas uma América do Norte e uma América do Sul, traçando o limite em algum local no Istmo do Panamá (umas vezes no Canal do Panamá, outras na fronteira entre o Panamá e a Colômbia e outras na fronteira entre Panamá e Costa Rica). Pela última definição, a América do Norte incluiria a América Central Continental e Insular (Caribe).",
    countryCount: 3,
    languages: 256,
    cities100: 27,
    cities: [
      {
        banner: "/north-america/orlando.jpg",
        capital: "Orlando",
        country: "Estados Unidos",
        image: "/north-america/usa.png",
      },
      {
        banner: "/north-america/cancun.jpg",
        capital: "Cancún",
        country: "México",
        image: "/north-america/mexico.png",
      },
      {
        banner: "/north-america/lasVegas.jpg",
        capital: "Las Vegas",
        country: "Estados Unidos",
        image: "/north-america/usa.png",
      },
      {
        banner: "/north-america/losAngeles.jpg",
        capital: "Los Angeles",
        country: "Estados Unidos",
        image: "/north-america/usa.png",
      },
      {
        banner: "/north-america/miami.jpg",
        capital: "Miami",
        country: "Estados Unidos",
        image: "/north-america/usa.png",
      },
      {
        banner: "/north-america/newYork.jpg",
        capital: "New York",
        country: "Estados Unidos",
        image: "/north-america/usa.png",
      },
      {
        banner: "/north-america/toronto.jpg",
        capital: "Toronto",
        country: "Canadá",
        image: "/north-america/canada.png",
      },
    ],
  },
  {
    name: "africa",
    translatedName: "África",
    carousel: "/africa/africa.jpg",
    banner: "/africa/africaPage.jpg",
    bannerTitle: " Continente com clima tropical e Grande biodiversidade..",
    description:
      "A África é o terceiro continente mais extenso (depois da Ásia e da América) com cerca de 30 milhões de quilômetros quadrados, cobrindo 20,3% da área total da terra firme do planeta. É o segundo continente mais populoso da Terra (atrás da Ásia) com cerca de um bilhão de pessoas (estimativa para 2005), representando cerca de um sétimo da população mundial, e 54 países independentes. Tem se transformado na ultima década em uma continente cada vez mais católico.",
    countryCount: 54,
    languages: 256,
    cities100: 27,
    cities: [
      {
        banner: "/africa/cairo.jpg",
        capital: "Cairo",
        country: "Egito",
        image: "/africa/egito.png",
      },
      {
        banner: "/africa/cidadeCabo.jpg",
        capital: "Cidade do Cabo",
        country: "África do Sul",
        image: "/africa/africaSul.png",
      },
      {
        banner: "/africa/joanesburgo.jpg",
        capital: "Joanesburgo",
        country: "África do Sul",
        image: "/africa/africaSul.png",
      },
      {
        banner: "/africa/hermanus.jpg",
        capital: "Hermanus",
        country: "África do Sul",
        image: "/africa/africaSul.png",
      },
      {
        banner: "/africa/madagascar.jpg",
        capital: "Madagascar",
        country: "Madagascar",
        image: "/africa/madagascarFlag.png",
      },
      {
        banner: "/africa/moçambique.jpg",
        capital: "Moçambique",
        country: "Moçambique",
        image: "/africa/moçambiqueFlag.png",
      },
    ],
  },
];
